name = "kahootplus-player"
compatibility_date = "2025-01-01"
account_id = "a3000146f2714841e3bdd91d655aef9c"
pages_build_output_dir = "dist"

[[env.production.routes]]
pattern = "quiz-player.rushelwedsivani.com/*"
custom_domain = true
